# Generated by Django 6.0.6 on 2026-06-19 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='content.sectiontype')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='sectiontype',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_types', to='content.subject'),
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True)),
                ('passage', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='task_groups/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_groups/img/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to='content.section')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('gap_fill', 'Gap fill'), ('matching', 'Matching'), ('short_answer', 'Short answer'), ('essay', 'Essay')], max_length=32)),
                ('prompt', models.TextField()),
                ('content', models.JSONField(blank=True, default=dict)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('explanation', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.taskgroup')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('time_limit', models.DurationField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='content.subject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.test'),
        ),
        migrations.AddConstraint(
            model_name='sectiontype',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='uniq_sectiontype_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('test', 'position'), name='uniq_section_position'),
        ),
    ]
